version: '3.8'

services:
  app:
    build: .
    container_name: pms
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: pmsbeUser
      POSTGRES_PASSWORD: 5T5CvQc
      POSTGRES_DB: pms
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: pmsbeUser
      POSTGRES_PASSWORD: 5T5CvQc
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres_data:
